export * from './task.interface'
export * from './finished-task.interface'
export * from './grade.interface'
export * from './student.interface'
export * from './mentor.interface'
export * from './getstudents.interface'
